### ISSUE TITLE
Workflow `test-compile` is running on forks

### ISSUE THREAD

**Issue by Fuzzy2319** [MonsterDruide1/OdysseyDecomp#178]
When I updated the main branch of my repository, I noticed that the "test-compile" workflow was running.
![image](https://github.com/user-attachments/assets/1450c571-aa1b-40b6-baf7-d0082a77bb41)
Shouldn't it be skipped like the other workflows?

**Comment by LynxDev2** [comment]
That got added an hour ago in #149. I guess @MonsterDruide1 forgot to add the check to see that the repo matches this one

**Comment by MonsterDruide1** [comment]
No, that one is fine to run on all repos. The others are skipped because they either require secrets or deployment keys that are only supplied on the main repo, but just checking whether the code can compile or if the compiler throws an exception can be done on any repo, without knowledge of secrets.
